In [27]:

import numpy as np

def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
    return sigmoid(x) * (1 - sigmoid(x))


X = np.array([[0.15, 0.54, 0.45],
              [0.32, 0.55, 0.7],
              [0.15, 0.03, 0.75]])

y = np.array([[0.32],
              [0.7],
              [0.5]])

weights_1 = np.random.random((3, 2)) - 0.5
weights_2 = np.random.random((2, 3)) - 0.5
weights_3 = np.random.random((3, 1)) - 0.5

result_error1 = 0;
result_error2 = 0;
result_error3 = 0;

num_iterations = 10000

for i in range(num_iterations):

    layer_1 = sigmoid(np.dot(X, weights_1))
    layer_2 = sigmoid(np.dot(layer_1, weights_2))
    layer_3 = sigmoid(np.dot(layer_2, weights_3))


    l3_error = y - layer_3
    

    layer_3_gradient = l3_error * sigmoid_derivative(layer_3)
    weights_3 += layer_2.T.dot(layer_3_gradient)

    l2_error = layer_3_gradient.dot(weights_3.T)

    layer_2_gradient = layer_3_gradient.dot(weights_3.T) * sigmoid_derivative(layer_2)
    weights_2 += layer_1.T.dot(layer_2_gradient)

    l1_error = layer_2_gradient.dot(weights_2.T)

    layer_1_gradient = layer_2_gradient.dot(weights_2.T) * sigmoid_derivative(layer_1)
    weights_1 += X.T.dot(layer_1_gradient)

    result_error3 = l3_error
    result_error2 = l2_error
    result_error1 = l1_error
    
print("")

print("------Досягнуте значення помилки-----")

print(result_error1)
print("")
print(result_error2)
print("")
print(result_error3)

print("Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)")
print(y)
print(layer_3)


------Досягнуте значення помилки-----
[[ 0.20831377 -0.16884511]
 [-0.21575355  0.1748753 ]
 [ 0.00743978 -0.00603018]]

[[-0.04974966  0.06908244  0.20659502]
 [ 0.05152644 -0.07154967 -0.21397341]
 [-0.00177677  0.00246723  0.00737839]]

[[-0.18666667]
 [ 0.19333333]
 [-0.00666667]]
Порівняння виходів (у) та вихідних данних за результатами навчання (layer_3)
[[0.32]
 [0.7 ]
 [0.5 ]]
[[0.50666667]
 [0.50666667]
 [0.50666667]]
